version: '3.4'

services:
  api:
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "5003:80"

  ui:
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=(db);Database=awkward;user=sa;password=awkward123;MultipleActiveResultSets=true"
    ports:
      - "5004:80"

  db:
    environment:
      SA_PASSWORD: "awkward123"
      ACCEPT_EULA: "Y"